### ISSUE TITLE
FS-NEXTRA error when interacting with settings.

### ISSUE THREAD

**Issue by sustained** [dirigeants/klasa#906]
### Describe the issue

```
2|vuebot  | [2020-01-20 13:08:49] Uncaught Promise Error: 
2|vuebot  | [2020-01-20 13:08:49] Error: FS-NEXTRA: /home/sustained/Projects/vue-land-bot/data/providers/json/clientStorage/*SNIP ID*.json already exists
2|vuebot  | [2020-01-20 13:08:49]     at copyOther (/home/sustained/Projects/vue-land-bot/node_modules/fs-nextra/dist/nextra/copy.js:81:19)
2|vuebot  | [2020-01-20 13:08:49]     at async startCopy (/home/sustained/Projects/vue-land-bot/node_modules/fs-nextra/dist/nextra/copy.js:58:9)
2|vuebot  | [2020-01-20 13:08:49]     at async Object.copy [as default] (/home/sustained/Projects/vue-land-bot/node_modules/fs-nextra/dist/nextra/copy.js:25:9)
2|vuebot  | [2020-01-20 13:08:49]     at async Object.move [as default] (/home/sustained/Projects/vue-land-bot/node_modules/fs-nextra/dist/nextra/move.js:42:13)
2|vuebot  | [2020-01-20 13:08:49]     at async writeFileAtomic (/home/sustained/Projects/vue-land-bot/node_modules/fs-nextra/dist/nextra/writeFileAtomic.js:16:5)
2|vuebot  | [2020-01-20 13:08:49]     at async Object.writeJSON [as default] (/home/sustained/Projects/vue-land-bot/node_modules/fs-nextra/dist/nextra/writeJSON.js:9:5)
2|vuebot  | [2020-01-20 13:08:49]     at async Map._save (/home/sustained/Projects/vue-land-bot/node_modules/klasa/src/lib/settings/SettingsFolder.js:364:4)
2|vuebot  | [2020-01-20 13:08:49]     at async Map.update (/home/sustained/Projects/vue-land-bot/node_modules/klasa/src/lib/settings/SettingsFolder.js:300:23)

```

### Code or steps to reproduce

Well, I'm doing something like this in my RFC service.
```ts
  /**
   * Cache the RFCs and then return them.
   *
   * Note that this does not bother to check the `CACHE_TTL` as `getAllRFCs` does.
   */
  async cacheRFCs(): Promise<PullsListResponseItem[]> {
    try {
      const rfcs = await github.paginate('GET /repos/:owner/:repo/issues', {
        owner: RFCService.OWNER,
        repo: RFCService.REPO,
        state: PullRequestState.ALL,
        sort: PullRequestSort.POPULARITY,
      })

      this.client.settings.update('rfcs.cachedAt', Date.now())
      this.client.settings.update('rfcs.cache', rfcs, {
        arrayAction: 'overwrite',
      })

      this.updateFuzzySearcher()

      this.rfcs = rfcs
      return this.rfcs
    } catch (error) {
      console.error(error)
      return []
    }
  }
```

And then that gets called on `init`.

The schema looks like this:

```ts
Client.defaultClientSchema.add('rfcs', rfcs => {
  return (
    rfcs
      /**
       * How long to wait before refetching the RFCs from Github?
       */
      .add('cacheTTL', 'number', { default: 1000 * 60 * 60 * 4 })
      /**
       * At what time were the RFCs cached?
       */
      .add('cachedAt', 'number')
      /**
       * The RFC cache.
       */
      .add('cache', 'any', { array: true })
  )
})
```

And I'm using the JSON provider (during development).

TBF it's a LOT of data (300KB), but I will be reducing that rather significantly, soon, as we are only using a small amount of it. So maybe that's what caused the issue? It's totally understandable if it isn't really designed for such large amounts of JSON, still - it should not throw errors.

It happened on init of my service, services are a custom piece (store) of mine - I don't think that code is really relevant but if it is then let me know.

### Expected and actual behavior

That an error isn't thrown when interacting with settings.

### Further details

- **discord.js version**: `master` (`6302afb84bb05907d12790280c6074ff850497a3`)
- **node.js version**: `v12.14.1`
- **Klasa version**: `settings`
- [ ] I have modified core files.
- [x] I have tested the issue on latest master. Commit hash: `aee79a51a6e845b6678e96fdd1a7cc1e27fda435`

**Comment by kyranet** [comment]
Change those:
```javascript
this.client.settings.update('rfcs.cachedAt', Date.now())
this.client.settings.update('rfcs.cache', rfcs, {
	arrayAction: 'overwrite',
})
```

To those, and your issue will be solved:
```javascript
await this.client.settings.update([
	['rfcs.cachedAt', Date.now()],
	['rfcs.cache', rfcs]
], { arrayAction: 'overwrite' });
```

The problem you were having is that you were calling `Settings#update` twice without awaiting, so it data races. If you awaited each one of them, it wouldn't data race and nothing bad would happen, but yeah, we can batch two writes in one!

**Comment by sustained** [comment]
Thanks so much!
